language: r
cache: packages
sudo: false
dist: trusty
warnings_are_errors: false
r:
  - bioc-release
  - bioc-devel
r_github_packages:
  - r-lib/covr
script: true
after_success:
  - Rscript -e 'covr::codecov()'
