# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

r:
  - bioc-release

os:
  - osx

# blocklist
branches:
  except:
  - develop

# safelist
# branches:
#   only:
#   - master

env:
  global:
    - LINTR_COMMENT_BOT=true
    - R_MAX_NUM_DLLS=150

# r_build_args: "--no-build-vignettes"
# r_check_args: "--no-vignettes"

# Set true before submission to Bioconductor
warnings_are_errors: true

# Temporarily enable to cache packages
# script: true

r_packages:
  - covr
bioc_packages:
  - BiocCheck
  - GenomeInfoDbData
  - S4Vectors
  - EnsDb.Hsapiens.v75
r_github_packages:
  - jimhester/lintr

after_success:
  - chmod +x travis_success.sh
  - ./travis_success.sh

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: always
