# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

r:
  - bioc-release
  - bioc-devel

# blocklist
branches:
  except:
  - develop

# before_install:
#   - sudo apt-get update

# External dependencies
# dependency for gsl > copula > zinbwave
addons:
  apt:
    update: true
    packages:
      - libgsl-dev

env:
  global:
    - LINTR_COMMENT_BOT=true
    - R_MAX_NUM_DLLS=150
    - _R_CHECK_FORCE_SUGGESTS_=true

# r_build_args: "--no-build-vignettes"
# r_check_args: "--no-vignettes"

# Set true before submission to Bioconductor
warnings_are_errors: true

# Temporarily enable to cache packages
# script: true

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: always

r_packages:
  - covr
bioc_packages:
  - BiocCheck
r_github_packages:
  - jimhester/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck .
