# R for travis
# https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: false

# Temporarily enable to cache R packages
# script: true

# Need to increase DLLs above default of 100
env:
  global:
    - R_MAX_NUM_DLLS=150

r:
  - bioc-release
  - bioc-devel
r_packages:
  - covr
  - rlang
r_github_packages:
  - steinbaugh/basejump@develop

after_success:
  - Rscript -e 'covr::codecov()'
